server {
    listen 80;
    listen 8080;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /kds {
        try_files $uri /kds.html;
    }

    location /booking {
        try_files $uri /booking.html;
    }

    location /menu {
        try_files $uri /menu.html;
    }

    location /customer-order {
        try_files $uri /customer-login.html;
    }

    location /oauth2/ {
        try_files $uri /index.html;
    }
}
